### PR TITLE
Post images

### PR DESCRIPTION
**Pull request by DRD161**
So far I have added an image to the "Healing power of nature" post in the English section. I will continue to look for a way to add a default image to the articles to be place holders until I finish adding the corresponding images

### CODE REVIEW

**Comment by andy5995** [comment]
Thanks for working on this, Dylan. Is it ready for review or will there be more commits?

**Comment by DRD161** [comment]
No problem glad to help out :) I was trying to make a change that was suggested by @sexybiggetje. He suggested that I align the images evenly to the right of the posts. I'm still working on it, I'm getting some odd behavior from the styles but I'm gonna mess around with it. I submitted this pull request so we can at least implement what I have so far. Aside from his suggestion it's just a matter of the corresponding images being add to the posts over time.

**Comment by andy5995** [comment]
>I'm still working on it, I'm getting some odd behavior from the styles but I'm gonna mess around with it.

You're doing that on this branch?

>I submitted this pull request so we can at least review and implement what I have so far while I work on his suggestion.

If I review and merge, that could make things a bit difficult if you're still working on this branch. If I did merge, would you easily be able to save any new changes?

**Comment by DRD161** [comment]
Yeah, I figured that if you merged this branch couldn't I continue to make changes on it and just submit another pull request later? Or would I need to make a new branch? Do branches disappear once merged? This is my first open source contribution so I'm learning as I go haha.

**Comment by DRD161** [comment]
Hey Andy, I'm having an issue with setting the images all to the right without pushing the buttons up on the posts. Can I submit a pull request and see if somebody can help me out with this issue?

**Comment by sexybiggetje** [comment]
Didn't check it out yet; but float: right should fix it probably. If it floats outside the box provide a padding on the right side of the image.

**Comment by DRD161** [comment]
@sexybiggetje this is what happens when I add float: right;

image

**Comment by DRD161** [comment]
Even with padding added to the right the positionbing is the same but the image gets squished a bit. Now if I add margin-left: 50%; the images all align evenly but their parent div pushes the buttons and such up like this:

image

**Comment by andy5995** [comment]
>Yeah, I figured that if you merged this branch couldn't I continue to make changes on it and just submit another pull request later? Or would I need to make a new branch? Do branches disappear once merged? This is my first open source contribution so I'm learning as I go haha.

Yes, in a way, branches disappear once they're merged. Basically if I merged it, then you added changes to the same branch on your end and re-submitted, it would contain the previous commits that were already merged. So basically creating unnecessary duplicates.

It seems that you're almost done, so I think it'll be easiest for you if you complete the changes on this branch, then we'll get everything merged at one time.

I'll assume @sexybiggetje will follow up with you tomorrow on the challenge you're having, but I'll ping @erichoog in Slack and see if he also can give some feedback.

I did pull this and merged it with a temp branch locally. Looks really cool so far!

**Comment by sexybiggetje** [comment]
Oh I see. I must check this out in order to say something about it. I'll look at it in the weekend if it still persists.

**Comment by sexybiggetje** [comment]
Pending my local changes..

Slack log for this ticket;

Ok first things first. Please, if you are going to display images at 100px*100px don’t add 4k images. They should be at most @2x, so 200x200px
And second, don’t do inline styles. They can be added to classes, inside style.css.
But let me figure this thing out.
Third, the image isn’t square, so that’s why you get an egg when relying on autosizing.
E.g. it should be indeed 100x100 or the image should be square. (Which anwsers your question on the ticket)
Fourth, are those royalty free images? Do they require named attribition, which we should note somewhere?
Fifth, if you float it right, it appears lower than the title. That’s because the element img has been given a generic margin. one needs to reset that.

**Comment by andy5995** [comment]
>Fourth, are those royalty free images? Do they require named attribition, which we should note somewhere?

@DRD161 What is the source of these images?

**Comment by DRD161** [comment]
The source is a site called unsplash. It's a photography site where the photographers allow their images to be used royalty and attribution free.

**Comment by andy5995** [comment]
Oh, cool. It would be nice if we added a link their license somewhere

https://unsplash.com/license

But that can be done later. From my interpretation, it's not required. I'll figure out where that should go (or it will be discussed in the chat), and it doesn't need to be part of this PR.

**Comment by andy5995** [comment]
Is this ready for review?

**Comment by sexybiggetje** [comment]
My changes are ammended in this pull request. So if someone wants to review, go ahead! :)

**Comment by andy5995** [comment]
This was closed by @DRD161 but the PR is now in #135

**Pull request closed without merging**
