### PR TITLE
started category for pt_BR #113

### PR DESCRIPTION
**Pull request by marioecg**
hey @andy5995 I submitted a PR for the issue asked for. If I am missing something please let me know 🙂.

### CODE REVIEW

**Comment by marioecg** [comment]
@andy5995 is it good #115 ? I just translated the markdown file, should I have added an original one? I see there isn't a category for Spanish, is it ok if I make it?

**Comment by andy5995** [comment]
> @andy5995 is it good #115 ? I just translated the markdown file, should I have added an original one? I see there isn't a category for Spanish, is it ok if I make it?

@marioecg I tested it locally and everything works!

And yes, please change it so the link leads to a native Brasilian Portuguese language mental health web site.

And yes, it would be great if you added a Spanish category as well. Please make that in a separate PR. Thank you!

**Comment by marioecg** [comment]
@andy5995 okay the translation is already for native BR PT, what am I missing? One last thing, when I add the PR for Spanish, should it address this same issue #113 or the PR #115?

Thanks Andy.

**Comment by andy5995** [comment]
>@andy5995 okay the translation is already for native BR PT, what am I missing?

Oh, we are not looking for a translation in this situation. We want to add a mental health web site that is for people who read Brasilian Portuguese.


>One last thing, when I add the PR for Spanish, should it address this same issue #113 or the PR #115?

Niether one. There is no issue (or ticket) for it and we don't need to create one. But you will create a separate pull request for it.

**Comment by marioecg** [comment]
@andy5995 got it! So what else should I do for this PR to be complete 🙂?

**Comment by andy5995** [comment]
Remove the post that contains the link to http://ahrp.org and replace it with a new post. The new post should be in the same format, but contains a link to a Brasilian Portuguese mental health site.

**Comment by marioecg** [comment]
@andy5995 done, correct?

**Comment by andy5995** [comment]
Thank you @marioecg !

**Pull request merged**
