### PR TITLE
Added alphabetical sorting of posts in EN category

### PR DESCRIPTION
**Pull request by dreamingblackcat**
Hi I've come across issue #33  and got curious about how it could be implemented. I did some research and found this example [https://github.com/sverrirs/jekyll-paginate-v2/tree/master/examples/02-category](https://github.com/sverrirs/jekyll-paginate-v2/tree/master/examples/02-category) in jeyll-paginate-v2 repo.
So, I tried to implement it for EN category and looks like it works.

So, my approach here is to use another category page for EN namely EN_alphabetcial which is identical to EN but with different sorting of posts. Then I added a simple partial to switch between those two differnt pages. It's at `includes/post_sorting_types.html` and it simple provided two links for switching between normal and alphabetical sorting.

The approach used the same strategy that you first described in the issue. I am new to this codebase and please do guide me along for any changes you would like to do.

### CODE REVIEW

**Comment by andy5995** [comment]
Whoa! I tested this. So cool!

One problem is that when the 'alphabetical' link is clicked, the language navbar at the top disappears.

And is there a way to do a reverse sort? So when clicking the link again, it reverses the order they are sorted?

Thank you @dreamingblackcat

**Comment by dreamingblackcat** [comment]
@andy5995 I am glad you like this. I'll look into the language navbar issue. For reverse sorting, we can do another category (eg. EN/alphabetical/desc) and another link on the partial. But, that would also end up generating another directory of posts in that order. If you don't mind that, I will add reverse sorting category too. What do you think?

**Comment by erichoog** [comment]
I'll try to take a look too.  Thanks for the PR!

**Comment by andy5995** [comment]
>For reverse sorting, we can do another category (eg. EN/alphabetical/desc) and another link on the partial. But, that would also end up generating another directory of posts in that order.

@dreamingblackcat Yes, that would be fine. I think that since this project keeps growing, we will need to start discussing methods for having it use a database instead of jekyll, but that may be in the distant future.

**Comment by erichoog** [comment]
@andy5995 we could also eventually switch to using a system like up-for-grabs.net uses it might be an option without the need to roll a full database.  But might not be practical as it grows as well.

**Comment by andy5995** [comment]
>If you don't mind that, I will add reverse sorting category too. What do you think?

@dreamingblackcat I'll wait to merge this until that's added. Right now the link to sort appears near the top, but after it's clicked the first time, it doesn't do anything.
Much better if it would flip the sort order.

@erichoog 

>@andy5995 we could also eventually switch to using a system like up-for-grabs.net uses it might be an option without the need to roll a full database. But might not be practical as it grows as well.

I don't think anyone has the "spark" right now necessary to start making big changes. ;) Maybe we'll start the discussion on Slack soon.

**Comment by andy5995** [comment]
ok @erichoog I look forward to this patch being completed. :)

**Comment by erichoog** [comment]
@andy5995 @dreamingblackcat  hold on, one thing I noticed is that when we select a different language other than EN, then the sorting link only points back to EN, I think we would want this to be dynamic depending on the language currently selected.  We may be able to parse the current language using a function in mhwkb-scripts.js file.  I'll take a look.

**Comment by dreamingblackcat** [comment]
@erichoog @andy5995 Thanks for the support into this PR. I haven't been able to get back to this PR during previous week. My apologies.

@erichoog Currently, the links only support for EN. So, we should either add a conditional check in `includes/post_sorting_types.html` or add sorting categories to other languages. I would recommend the first option for now.

**Pull request merged**
