### PR TITLE
Language nav

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@erichoog wrote on #94 
>So I'm not 100% this fully closes #35 but I believe so.

>There are a good few issues with this still such as:
- it automatically sets the language to English where a placeholder would be nice
- the design doesn't match the rest of the boostrap nav buttons for the dropdown
- it may not work perfectly with mobile
- managing the script I created could become tedious if lots of languges are added or if there is a change in the url or categories

>One thought I had was that if it doesn't work great in the navbar we could always just replace the buttons above the posts.

I realized it's going to be a problem if it defaults to English. If a English-speaking user sees it set to English, they wouldn't feel a need to select it again, and thus never be sent to https://mhwkb.github.io/category/EN/

**Comment by andy5995** [comment]
@sexybiggetje @erichoog Is it time to close this? I forgot what we all had decided about it. Maybe another approach should be used after focus has been restored? ;)

**Comment by sexybiggetje** [comment]
I'm unsure if I ever was aware of this ticket. When I worked on it, that was either trough slack or on another ticket. If these points are still valid (I think they are?) keep it open.

**Comment by andy5995** [comment]
>I'm unsure if I ever was aware of this ticket. When I worked on it, that was either through slack or on another ticket. If these points are still valid (I think they are?) keep it open.

@sexybiggetje , this was something @erichoog had started. He made a PR. You had said you would take a look at when you had time. I accidentally merged it too early. He was going to recreate the PR, but for some reason rebasing didn't work. I was able to cherry-pick the PR and recreate it from my fork. And then I think we all got side-tracked. :)

**Comment by andy5995** [comment]
These are the screenshots @erichoog had in his original PR:

image

image

**Comment by andy5995** [comment]
I'm going to live dangerously and merge this. If there are any issues afterward, individual tickets can be made to address them.

**Comment by andy5995** [comment]
Oh, ok! That makes sense, and thank you for the correction. Could you make the change?

**Comment by ritwik12** [comment]
@andy5995 I don't think so, I've tried but I saw that we are using "navbar-btn bfh-selectbox bfh-languages"
which is a language list of bootstrap form Helpers. So I don't think we can alter that easily.

**Comment by andy5995** [comment]
>I don't think so, I've tried but I saw that we are using "navbar-btn bfh-selectbox bfh-languages"
which is a language list of bootstrap form Helpers. So I don't think we can alter that easily.

@ritwik12 Still, thank you for the information. Would you mind opening an issue for it?

**Comment by ritwik12** [comment]
@andy5995 Your welcome.Yeah I'll do that :)

**Pull request merged**
