### PR TITLE
Language Selector (Closes #35)

### LINKED ISSUE #35: change style of category (language) links
move category display to header

This needs to get moved (L4)

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_layouts/home.html#L4

and placed in

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_includes/header.html#L5

That will make sure the LANG buttons will show up on tag pages, as well as category pages.

Also if anyone feels the style could be improved upon, that could be part of this ticket.

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_includes/category_display.html#L10

This is our logo that @jamielthompson29 made.

https://github.com/mhwkb/mhwkb.github.io/blob/master/images/mhwkb_dharma_wheel_logo_406x384.png

So any new styles should not conflict with the color scheme of the logo.

### PR DESCRIPTION
**Pull request by erichoog**
So I'm not 100% this fully closes #35 but I believe so.

There are a good few issues with this still such as:
- it automatically sets the language to English where a placeholder would be nice
- the design doesn't match the rest of the boostrap nav buttons for the dropdown
- it may not work perfectly with mobile
- managing the script I created could become tedious if lots of languges are added or if there is a change in the url or categories

One thought I had was that if it doesn't work great in the navbar we could always just replace the buttons above the posts.

@andy5995 it's up to you if you want to merge this or continue to work on it here.

image

image

### CODE REVIEW

**Comment by andy5995** [comment]
>It may not work perfectly with mobile

>managing the script I created could become tedious if lots of languages are added or if there is a change in the url or categories

Thank you for working  on it. Sounds like more discussion about how to implement this would be a good course. Let it sit for a few days.

**Comment by escottalexander** [comment]
So excited to see all the progress. Are there plans to eventually have the browser default to the proper language for the region where the IP is coming from? Maybe a little further out of a goal, but it is possible.

**Comment by andy5995** [comment]
Closed by accident. I made some recent commits while on the wrong branch. (ping #35)

**Comment by andy5995** [comment]
This shows as merged, but I reversed it. Eric could you make the PR again when you it's convenient for you?

cc: @sexybiggetje

**Comment by erichoog** [comment]
Hey @andy5995 it still appears to be on the live site but I guess it just hadn't been rebuilt?

I can do this fairly quickly I think I'll create a new one and just reference this PR

**Comment by andy5995** [comment]
>So excited to see all the progress. Are there plans to eventually have the browser default to the proper language for the region where the IP is coming from? Maybe a little further out of a goal, but it is possible.

Thanks @escottalexander :) And I created a ticket from your suggestion (#97)

**Pull request merged**
