### PR TITLE
dropdown tag menu added to posts

### PR DESCRIPTION
**Pull request by escottalexander**
Lots of little changes made to make this a possibility. Please look over carefully. One of the biggest things is that we are now pulling in the JS for bootstrap in the bottom of footer.html.

### CODE REVIEW

**Comment by escottalexander** [comment]
I just noticed I forgot to run beautify on some of the files. Sorry about that. We will get to it eventually, I'm sure.

**Comment by andy5995** [comment]
I'd like to see more color in the tags, but I'm not sure which ones yet. :) But I really like that style!! Thanks!

How did it look when you tested it locally with Jekyll?

**Comment by escottalexander** [comment]
Ok, I think I did what you wanted. Just let me know. I am a bit clueless.

**Comment by andy5995** [comment]
When I tested it, this is what I saw when I scrolled to the bottom. And it shows every post in the EN directory.

screenshot_2017-11-06_17-35-19

But I really like where this patch is headed!

**Pull request merged**
