### PR TITLE
Create Tooltips 

### PR DESCRIPTION
**Pull request by ritwik12**
Create Tooltips for
EN, DE, HI, NL, SV, NE, pt_BR

### CODE REVIEW

**Comment by ritwik12** [comment]
#116

**Comment by ritwik12** [comment]
screenshot 2

**Comment by ritwik12** [comment]
Sorry for the long code in CSS, please make it short if you feel problem with code length.

**Comment by andy5995** [comment]
Thank you for your generosity, @ritwik12 , but this is already being addressed in #102 . 102 is on hold until there is more discussion about the issues mentioned.

Also, the changes you submitted would have to be in the same PR, not 2 separate ones.

What do you think of #102 ? Do you have an opinion on if that would meet the needs you believe should be addressed?

**Comment by ritwik12** [comment]
@andy5995 ohk 😅.. Then I guess my work got wasted 😂

**Comment by ritwik12** [comment]
I'll

**Comment by andy5995** [comment]
https://github.com/mhwkb/mhwkb.github.io/blob/master/CONTRIBUTING.md#inquiring-about-an-issue

**Pull request closed without merging**
