### PR TITLE
Initial implementation simple-jekyll-search.js

### PR DESCRIPTION
**Pull request by erichoog**
Here's an initial implementation of the [simple-jekyll-search.js project ](https://github.com/christian-fei/Simple-Jekyll-Search).  For #63 

Not ready to be merged yet but shows the functionality.

The template for the search display will need to setup still and see if we like the fuzzysearch options that are there by default.

### CODE REVIEW

**Comment by andy5995** [comment]
Very cool! Thanks!

Looks like comment tags are a good thing thing to have around script tags.

https://www.w3schools.com/TAGS/tag_comment.asp

**Comment by erichoog** [comment]
@andy5995 that's a good idea for sure, I literally just copied the snippet out of their documentation but certainly doesn't hurt to be safe with it.

**Comment by andy5995** [comment]
I went ahead and resolved a merge conflict, but now I realize I should have just waited until you were done.

Shouldn't be a problem unless you're currently working on it.

If not, just use `git pull` to update your working branch with my changes. If you run into trouble, best wait for me.

I'm sorry if I caused any problems here.

**Comment by andy5995** [comment]
>Not ready to be merged yet but shows the functionality.

>The template for the search display will need to setup still and see if we like the fuzzysearch options that are there by default.

We could merge it as is, and maybe get more feedback about the options from more people.

Also, the template design can be tweaked after it's merged. Maybe someone would be interested in prettying up the template. :)

Did you want to do some more work on it though?

**Comment by erichoog** [comment]
No worries about the fixes on the PR I'm sure it'll be fine.  I'll see if I can get it working a little better and then merge it in if that works? Hoping to work on it a bit tonight.

**Comment by andy5995** [comment]
>'ll see if I can get it working a little better and then merge it in if that works?

Sure, just merge in it when you think it's ready.

**Pull request merged**
