### PR TITLE
Styling improvements for #95.

### PR DESCRIPTION
**Pull request by sexybiggetje**
Styling changes for #95.
- Removes dropdown and adds them to a tag based view to improve clicktrough rate.
- Tag buttons flow on mobile devices
- Re styles the panel divs, so they aren't bright blue any more. I've kept a border in this color.
- Simplifies generated HTML

Tablet size:
issue-95-tablet-size

Mobile size:
issue-95-mobile-size

### CODE REVIEW

**Comment by sexybiggetje** [comment]
Ugh, why do they keep on being conflicted. I just merged them with master and pressed resolved.

**Comment by andy5995** [comment]
It seems your editor was stripping the newline from the end of both files. Git saw a change at that location and couldn't resolve it.

I'd explain it more clearly, but that's the best I can do. Suffice it to say, once I added a newline, the merge conflict went away.

screenshot_2017-11-17_13-54-17

The red circle and arrow indicates no newline was detected.

**Comment by JedMeister** [comment]
@sexybiggetje - not sure what OS or editor you are using, but that is pretty common behaviour for Windows editors. As noted by @andy5995 - Linux files require a newline as the last character of a file. You should be able to workaround that by manually adding a new line to the end of a document. OTOH, your editor of choice may allow you to set it to auto include those for Linux files. And/or get a better text editor!

Personally, I only use Vim these days, but I'm a Linux commandline user so YMMV. If you're on Windows, the best text editor IMO was Notepad++.

**Comment by sexybiggetje** [comment]
@JedMeister I've merged the conflicts with the web editor on Github.

**Comment by erichoog** [comment]
@sexybiggetje looks awesome!

**Comment by sexybiggetje** [comment]
@erichoog thanks :)

**Comment by andy5995** [comment]
For the record...

First, I tried resolving the merge conflicts by pulling your branch. It seemed to work, but after I pushed the change, the conflict showed up again.

After a little examination, I had a hunch about that newline problem, so in the GitHub editor, I removed them (which can be seen in the last 2 commits on the patch).

I guess I don't know when the newline got stripped away or if it never had one; it just so happened your changes were at the end of the file so it suddenly became a problem.

**Pull request merged**
